language: rust
dist: xenial
rust:
  - stable
cache: cargo
addons:
  apt:
    packages:
      - musl-tools
before_script:
  - cd native
  - rustup target add x86_64-unknown-linux-musl
script:
  - cargo build --release --target x86_64-unknown-linux-musl
deploy:
  provider: releases
  api_key:
    secure: OWrBtdCLLDYIuP85zPQniJLpuS4SKKew4X0LYGfuTlNEHxzAO27PBUameuns4d6Z+CjkE8QLIzaRJgCuA6oqPVgLOIPhZ/KKo70GNBMlKMtBJa6i9QzfvBCmfQPSM7RYhz11qEUDBMupYVsHXlXm4PqgbuC2m9b9YXNP0yxeiVjI9v5mf0dDiyqbgJlkgUzvsMI6rckfBMSB5nahpjOCLcsceElJtHu97eqg3GvvaC/Z+KCKNG2bjH+SoRiAgJ8cCDE0O9c0FchY93lw8hXmW19ksAdkHIB5TUlyrxRNqJyOkh+OGYmz1pZQu4La/PULdT+KBu10Vy4Amz1mL+ch44+T641/jKnkKu4TpWnCjrL9Ep9DkcgjuYaWwxOxT2AX+8fAroJp27e77qgp+qkpoOk/xjBLkJqkqdas5zC+EmtFBam8T2VJihFv0EZr2/3rb0tUku731S6HjLnA+0cIToGoGyl0rC1M4+x1e7eIn7mv6018bNQeFPrsGMxd3uxQOnRYsitkp1pj4snZfhyEXJB6NtLUW6Y7sGtwHwA5JENrfYL/9WEWIpHYaFRPpuzp0XJXlMvwjnWJJZC/YyF6HUMN/pyUhtEeQEudt1B70qLQX8UWyzS7ZBayp3sT3Gy52mYYn7yBZSn/h5fSAK0z6Au0eG7szqYLXwfgXvSOsDQ=
    file: ./target/wasm32-unknown-unknown/release/octolo
  on:
    tags: true
